
java_binary(
    name = "junit_runner",
    main_class = "build.please.main.TestMain",
    visibility = ["PUBLIC"],
    deps = [
        "//tools/junit_runner/src/main/java:lib",
    ],
    labels = ["hlink:plz-out/package"],
)
