plugin_repo(
    name = "java",
    revision = "master",
    plugin = "java-rules",
    owner = "please-build",
    hashes = [],
    # Change this to a specific revision to avoid changes breaking your build unexpectedly
)
