TOOLS_VERSION = "1.0.0"

remote_file(
    name = "junit_runner",
    url = f"https://github.com/please-build/java-rules/releases/download/tools-v{TOOLS_VERSION}/junit_runner.jar",
    hashes = ["6d9afc4054419fe08677feed093d5cbd7e4098d68d59087e34c2bd3e4a52c4d6"],
    visibility = ["PUBLIC"],
)