# TODO(jpoole): This should be a remove file on the plugin repo's release page and we should remove //_please:javac_worker
filegroup(
    name = "javac_worker",
    srcs = ["@//_please:javac_worker"],
    visibility = ["PUBLIC"],
    labels = ["hlink:plz-out/package"]
)